<div class="c-top-content">
	<img alt="" src="/adminCJI/img/logo-new.jpg" class="c-top-left">
	<div class="c-top-right">
		<ul>
		    <?php if(isset($this->userInfo)):?>
		    <li>欢迎您：<span class="c-top-name"><?php echo $this->userInfo->admin_email?></span></li>
		    <li><a href="/admin/admin/logout" class="m-titlielogout">注销</a></li>
		    <?php else :?>
<!--		    <li><a href="/admin/login">未登录</a></li>-->
	        <li><a href="/admin/admin/login">登录</a></li>
		    <?php endif;?>
		</ul>
	</div>
</div>