<!--表格-->
<table id="dg" title=" " class="easyui-datagrid"
       style="width: 100%; height: 680px"
       url="/crontab/index/listtask"
       method="post"
       isJsonStr="true"
       toolbar="#toolbar"
       rownumbers="true"
       fitColumns="true"
       singleSelect="true"
       idField="ID"
       pagination="true"
       panelHeader="false">
    <thead>
    <tr>
        <th field="ck" checkbox="true"></th>
        <th field="NAME" sortable="true" width="89%">日志文件</th>
        <th field="operation" sortable="true" width="5%" data-options="formatter: edit">操作</th>
    </tr>
    </thead>
</table>

<script>
    function edit(val, row, index)
    {
        return "<a href='/admin/down-log?file_name="+row['file_name']+"'>下载</a>";
    }
</script>