<html>
<head>
    <title>Hello World</title>
    <script src="/webCJI/js/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script src="/webCJI/js/js-cookie.js" type="text/javascript"></script>
    <script src="/webCJI/dotjs/dot.js" type="text/javascript"></script>
    <script src="/webCJI/views/layout/layout.js"   type="text/javascript"></script>
    <script src="/webCJI/easyUI/jquery.easyui.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $().ready(function(){
            alert("This is in ready");
         });
    </script>
</head>
<body>
       <div id="id-div"></div>
</body>
</html>