<!DOCTYPE html>
<html lang="zh_cn">
<head>
	<title>耀领数据-后台管理</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <!-- CSS -->
<link href="/adminCJI/css/default/web.css" rel="stylesheet"type="text/css" />
<link href="/adminCJI/css/default/trede.css" rel="stylesheet"type="text/css" />
<link href="/adminCJI/easyUI/themes/blove/easyui.css" media="screen" rel="stylesheet" type="text/css"/>
<link href="/adminCJI/easyUI/themes/icon.css" media="screen" rel="stylesheet" type="text/css"/>
<link href="/adminCJI/css/default/bank.css" rel="stylesheet"type="text/css" />
<link href="/adminCJI/css/default/alertmassge.css" rel="stylesheet"type="text/css" />
<link href="/adminCJI/css/default/loding.css" rel="stylesheet"type="text/css" />
<link rel="shortcut icon"  href="/adminCJI/img/favicon.ico"  type="image/x-icon"/>

<!-- JS -->
<script src="/adminCJI/js/jquery-2.1.4.min.js" type="text/javascript"></script>
<script src="/adminCJI/easyUI/jquery.easyui.min.js" type="text/javascript" ></script>
<script src="/adminCJI/js/md5-min.js"></script>
<script src="/adminCJI/js/jquery-ex.js" type="text/javascript"></script>

</head>
<body>
	<div class="c-top-box">
		<div class="c-top-wrapper">
            <?php  echo $this->top;?> 
		</div>
	</div>
	<div class="c-main-box">
		<div class="c-main-wrapper">
			<div class="c-main-content">
				<div class="c-main-left"> 
                    <?php  echo $this->leftMenu;?>     
                </div>
				<div class="c-main-right"> 
                	<?php  echo $this->content;?>	       
                </div>
			</div>
		</div>
	</div>

	<div class="c-bottom-box">
		<div class="c-bottom-wrapper">
			<div class="c-bottom-content">
				<div class="m-footer-left">
					<div class="m-footer-words">
						<span>评级实验室</span> <span>帮助文档</span> <span>耀领博客</span> <span>联系我们</span>
						<span>媒体报道</span>
					</div>
					<div class="m-footer-wordsbottom m_footer_color">
						<div>
							<span class="m_footer_color">copyright@2016耀领(天津)科技有限公</span>&nbsp;<span class="m_footer_color">版权所有</span>&nbsp;&nbsp;<span class="m_footer_color">ICP津备234567190号-1</span>
						</div>
						<div>
							<span class="m_footer_color">隐私条款</span>&nbsp;&nbsp;服务条款
						</div>
					</div>
				</div>
				<div class="m-footer-right">
					<img class="m-footererweima" src="/webCJI/img/erweima.png">
				</div>
			</div>
		</div>
	</div>
</body>
</html>