<!DOCTYPE html>
<html lang="zh_cn">
<head>
    <title>耀领数据</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <!-- CSS -->
    <link href="/adminCJI/css/default/web.css" rel="stylesheet"
	   type="text/css" />
    <link href="/adminCJI/css/default/lender.css" rel="stylesheet"
	   type="text/css" />
    <link href="/adminCJI/easyUI/themes/blove/easyui.css" media="screen"
	   rel="stylesheet" type="text/css" />
    <link href="/adminCJI/easyUI/themes/icon.css" media="screen"
	   rel="stylesheet" type="text/css" />
    <link rel="shortcut icon"  href="/adminCJI/img/favicon.ico"  type="image/x-icon" />
    <!-- JS -->
    <script src="/adminCJI/js/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script src="/adminCJI/easyUI/jquery.easyui.min.js" type="text/javascript"></script>
    <!-- icon -->
    <link href="/adminCJI/img/m-logo.png" rel="shortcut icon" type="imagend.microsoft.icon">
</head>
<body>
	<!--顶部-->
	<div class="c-lender-box">
		<div class="c-top-lender-box">
		</div>
		<div class="c-main-lender-box">
		   <div class="c-main-lender-left">
		      <?php  echo $this->leftMenu;?>
		   </div>
		   <div class="c-main-lender-right">		   
		      <?php  echo $this->content;?>
		   </div>
		</div>
	</div>
</body>
</html>