<html>
<head>
    <script src="/webCJI/js/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                method: "POST",
                url: "/crontab/index/listtask",
                data:"",
                timeout: 20000,// 超时时间
                beforeSend: function () {
                },
                success: function (data) {
                    for(var i = 0; i < data.length; i++){
                        console.log(data[i]['ID']);
                        console.log(data[i]['NAME']);
                    }
                },
                complete: function () {
                },
                error: function () {
                    alert("请求出错了,请稍候再试");
                }
            });
        });
    </script>
</head>
<body>
<table>
    <!--        --><?php //foreach($this->result as $key=>$value){ ?>
    <!--            <tr><td>--><?php //$value; ?><!--</td></tr>-->
    <!--        --><?php //} ?>
</table>
</body>
</html>