<head>
    <link href="/webCJI/css/timing.css" rel="stylesheet" type="text/css" />
</head>
<div class="time_title">
    <button class="time_btn">创建任务</button>
</div>
<div class="time_content">
    <div class="time_list">
        <table class="time_tab">
            <tbody>
            <tr class="list_log">
                <td>任务名称</td>
                <td>开始时间</td>
                <td>结束时间</td>
            </tr>
            <tr class="list_con">
                <td>次日付款任务</td>
                <td>2016/06/28<span>13:55:08</span></td>
                <td>2016/06/28<span>13:55:08</span></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
