<head>
    <link href="/webCJI/css/timing.css" rel="stylesheet" type="text/css" />
</head>
<div class="time_title">
    <button class="time_btn">创建任务</button>
</div>
<div class="time_content">
    <div class="time_list">
        <div class="time_margin">
            <table class="time_tab">
                <tbody>
                <tr class="list_log">
                    <td>任务名称</td>
                    <td>开始时间</td>
                    <td>结束时间</td>
                </tr>
                <tr class="list_con">
                    <td>次日付款任务</td>
                    <td>2016/06/28<span>13:55:08</span></td>
                    <td>2016/06/28<span>13:55:08</span></td>
                </tr>
                <tr class="list_con">
                    <td>次日付款任务</td>
                    <td>2016/06/28<span>13:55:08</span></td>
                    <td>2016/06/28<span>13:55:08</span></td>
                </tr>
                <tr class="list_con">
                    <td>次日付款任务</td>
                    <td>2016/06/28<span>13:55:08</span></td>
                    <td>2016/06/28<span>13:55:08</span></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!--弹出框-->
    <div class="alert_cont" style="margin-left:-300px; margin-top:-200px;">
        <div class="alert_title">
            <div class="title_word">创建开机任务</div>
            <div><img src="/webCJI/img/btn_close_layer.png" class="close_btn" /></div>
        </div>
        <div class="detail">
            <div class="oder_details">
                <div class="oder_details_main">
                    <div class="oder_details_main_list">
                        <div class="m_label">名字：</div>
                        <div class="m_word">
                            <input class="choose input" type="text"/>
                        </div>
                    </div>
                    <div class="oder_details_main_list">
                        <div class="m_label">类型：</div>
                        <div class="m_word">
                            <select class="choose">
                                <option>定时关机</option>
                            </select>
                        </div>
                    </div>
                    <div class="oder_details_main_list">
                        <div class="m_label">开始时间：</div>
                        <div class="m_word">
                            <select class="choose">
                                <option>now</option>
                                <option>明天</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="oder_details_de">
                    <div class="oder_details_de_list">
                        <div class="m_label">时间间隔:</div>
                        <div class="m_word">
                            <select class="choose">
                                <option>now</option>
                                <option>明天</option>
                            </select>
                        </div>
                    </div>
                    <div class="oder_details_de_list">
                        <div class="m_label">结束时间:</div>
                        <div class="m_word">
                            <select class="choose">
                                <option>now</option>
                                <option>明天</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="alert_body"></div>
</div>
